name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'lib/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run tests
        run: cargo test
