name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'dist-proxy/**'
      - 'examples/vite/**'
      - '.github/workflows/deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  deploy:
    # prevents this action from running on forks
    if: github.repository == 'bluwy/fmu'
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm
        run: npm run build
      - name: Install dependencies
        run: npm install
        working-directory: examples/vite
      - name: Build site
        run: npm run build -- --base /fmu/
        working-directory: examples/vite
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Deploy site
        run: |
          git init
          git checkout -b site
          git add -A
          git commit -m 'deploy'
          git remote set-url --push origin https://bluwy:$${{ secrets.GITHUB_TOKEN }}@github.com/bluwy/fmu
          git push -f origin site:gh-pages
        working-directory: examples/vite/dist
